package io.github.dhoondlayai.artifact.json.codegen;

import io.github.dhoondlayai.artifact.json.model.*;
import java.util.*;

/**
 * ðŸ› ï¸ Reverse Engineering API: Automatically generates Java Code natively
 * from
 * a JSON string.
 * This is a massive timesaver. You no longer need to use external websites to
 * generate
 * your ViewModels or DTOs from huge API Responses.
 */
public class JsonCodeGenerator {

    /**
     * Generates Java Records source code directly from a given JsonNode.
     * 
     * @param className The name of the root Java class to create.
     * @param root      The JsonNode to inspect.
     * @return The formatted Java source code representing the JSON structure.
     */
    public static String generateJavaRecords(String className, JsonNode root) {
        StringBuilder output = new StringBuilder();
        output.append("// Auto-generated by artifact-json\n\n");
        generateInner(className, root, output, new HashSet<>());
        return output.toString();
    }

    private static void generateInner(String className, JsonNode node, StringBuilder sb, Set<String> created) {
        if (created.contains(className))
            return;
        created.add(className);

        if (node instanceof JsonObject obj) {
            sb.append("public record ").append(className).append(" (\n");

            List<String> fields = new ArrayList<>();
            obj.fields().forEach((k, v) -> {
                String type;
                if (v instanceof JsonValue val) {
                    type = getBasicType(val.value());
                } else if (v instanceof JsonObject) {
                    type = capitalize(k);
                    generateInner(type, v, sb, created); // Recurse
                } else if (v instanceof JsonArray arr) {
                    if (arr.elements().isEmpty()) {
                        type = "java.util.List<Object>";
                    } else {
                        JsonNode first = arr.elements().get(0);
                        if (first instanceof JsonObject) {
                            String itemType = capitalize(k) + "Item";
                            generateInner(itemType, first, sb, created);
                            type = "java.util.List<" + itemType + ">";
                        } else if (first instanceof JsonValue fp) {
                            type = "java.util.List<" + getBasicType(fp.value()) + ">";
                        } else {
                            type = "java.util.List<Object>";
                        }
                    }
                } else {
                    type = "Object";
                }
                fields.add("    " + type + " " + escapeKey(k));
            });
            sb.append(String.join(",\n", fields)).append("\n) {}\n\n");
        } else if (node instanceof JsonArray arr && !arr.elements().isEmpty()) {
            // Usually we generate from the first array item if root is an array
            generateInner(className, arr.elements().get(0), sb, created);
        }
    }

    private static String getBasicType(Object val) {
        if (val == null)
            return "Object"; // Unknown
        if (val instanceof String)
            return "String";
        if (val instanceof Double || val instanceof Float)
            return "double";
        if (val instanceof Long || val instanceof Integer)
            return "int";
        if (val instanceof Boolean)
            return "boolean";
        return "Object";
    }

    private static String capitalize(String s) {
        if (s == null || s.isEmpty())
            return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    private static String escapeKey(String k) {
        // Handle snake_case to camelCase inside record fields roughly
        if (k.contains("_")) {
            String[] parts = k.split("_");
            StringBuilder j = new StringBuilder(parts[0]);
            for (int i = 1; i < parts.length; i++) {
                j.append(capitalize(parts[i]));
            }
            return j.toString();
        }
        return k;
    }
}
